### ISSUE TITLE
Informations about dynamic libs

### ISSUE THREAD

**Issue by FreshXOpenSource** [mitghi/phantomjs-2.0.0-armv7#1]
Can you please provide more information on what platform / derivate you build PhantomJS?

It depends on about 20 dynamic libs (libexpat, libicu, libfontconfig, libfreetype, libjpeg, libpng, libssl) and it whould be helpful to know where to get them from.

Thanks!

**Comment by mitghi** [comment]
Hi,
This binary is built on Ubuntu 14.04 .
Just install the following packages and you are good to go:

sudo apt-get install flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libX11-dev libxext-dev
